name: BearShell Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: pipeline/tests.yml  # This will reference the 'tests.yml' file
    with:
      python-version: '3.11'
  publish:
    uses: pipeline/publish.yml  # This will reference the 'tests.yml' file
    with:
      python-version: '3.11'